# Generated by Django 2.0.4 on 2020-10-11 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeoJSON',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='LinearRing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geojson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='osm_database.GeoJSON')),
            ],
        ),
        migrations.CreateModel(
            name='LineString',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geojson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='osm_database.GeoJSON')),
            ],
        ),
        migrations.CreateModel(
            name='MultiLineString',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geojson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='osm_database.GeoJSON')),
                ('linestrings', models.ManyToManyField(to='osm_database.LineString')),
            ],
        ),
        migrations.CreateModel(
            name='MultiPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='MultiPoligon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geojson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='osm_database.GeoJSON')),
            ],
        ),
        migrations.CreateModel(
            name='OsmEntity',
            fields=[
                ('osm_id', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('osm_type', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('display_name', models.CharField(max_length=1024)),
                ('place_id', models.IntegerField()),
                ('place_rank', models.IntegerField()),
                ('importance', models.FloatField()),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('left', models.FloatField()),
                ('bottom', models.FloatField()),
                ('right', models.FloatField()),
                ('top', models.FloatField()),
                ('geojson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='osm_database.GeoJSON')),
            ],
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geojson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='osm_database.GeoJSON')),
            ],
        ),
        migrations.CreateModel(
            name='PointList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Polygon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exterior_ring', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exterior', to='osm_database.LinearRing')),
                ('geojson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='osm_database.GeoJSON')),
                ('interior_rings', models.ManyToManyField(related_name='interiors', to='osm_database.LinearRing')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='point',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='osm_database.Position'),
        ),
        migrations.AddField(
            model_name='multipoligon',
            name='polygons',
            field=models.ManyToManyField(to='osm_database.Polygon'),
        ),
        migrations.AddField(
            model_name='multipoint',
            name='coordinate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='osm_database.Position'),
        ),
        migrations.AddField(
            model_name='multipoint',
            name='geojson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='osm_database.GeoJSON'),
        ),
        migrations.AddField(
            model_name='linestring',
            name='positions',
            field=models.ManyToManyField(to='osm_database.Position'),
        ),
        migrations.AddField(
            model_name='linearring',
            name='positions',
            field=models.ManyToManyField(to='osm_database.Position'),
        ),
    ]
