# Generated by Django 2.0.4 on 2021-04-10 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('osm_database', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('osm_id', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('lat', models.DecimalField(decimal_places=18, max_digits=22)),
                ('lon', models.DecimalField(decimal_places=18, max_digits=22)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TagName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TagValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='tag',
            name='k',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='osm_database.TagName'),
        ),
        migrations.AddField(
            model_name='tag',
            name='v',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='osm_database.TagValue'),
        ),
        migrations.AddField(
            model_name='node',
            name='tags',
            field=models.ManyToManyField(related_name='interiors', to='osm_database.Tag'),
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('k', 'v')},
        ),
    ]
