# Generated by Django 2.0.4 on 2021-04-10 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osm_database', '0002_auto_20210410_0520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='osmentity',
            name='bottom',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='osmentity',
            name='importance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='osmentity',
            name='left',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='osmentity',
            name='place_rank',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='osmentity',
            name='right',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='osmentity',
            name='top',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
