# Generated by Django 2.0.4 on 2021-06-23 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osm_database', '0003_auto_20210410_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='osmentity',
            name='osm_id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='osmentity',
            unique_together={('osm_type', 'osm_id')},
        ),
    ]
