# Generated by Django 2.0.4 on 2021-10-17 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osm_database', '0004_auto_20210623_0119'),
    ]

    operations = [
        migrations.AddField(
            model_name='osmentity',
            name='id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
