# Generated by Django 2.0.4 on 2021-10-17 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osm_database', '0005_osmentity_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='osmentity',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='osmentity',
            name='osm_id',
            field=models.BigIntegerField(),
        ),
    ]
