# Generated by Django 2.0.4 on 2021-10-17 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osm_database', '0006_auto_20211017_0406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='osmentity',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
