# Generated by Django 2.0.4 on 2021-11-11 23:51

from django.db import migrations, models
import django.db.models.deletion
import root.models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.AutoField(auto_created=True, editable=False, max_length=255, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('percentage_maori', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, root.models.AutoSetterGetterMixin),
        ),
        migrations.RemoveField(
            model_name='page',
            name='content',
        ),
        migrations.AlterField(
            model_name='newspaper',
            name='id',
            field=models.AutoField(auto_created=True, editable=False, max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='page',
            name='id',
            field=models.AutoField(auto_created=True, editable=False, max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='publication',
            name='id',
            field=models.AutoField(auto_created=True, editable=False, max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='sentence',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrape.Page'),
        ),
    ]
