# Generated by Django 2.0.4 on 2021-11-14 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape', '0002_auto_20211111_2351'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='content',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
